### ISSUE TITLE
Configure Production Environment

### ISSUE THREAD

**Issue by Matheus-Homem** [Matheus-Homem/compass_project#70]
- [ ] Configure and prepare the production environment to receive the virtual environment and run the project
- [ ] Transfer the configured virtual environment to the production server
- [ ] Perform testing on the production environment to ensure the project is functioning as expected
