### ISSUE TITLE
Create `make` Commands

### ISSUE THREAD

**Issue by Matheus-Homem** [Matheus-Homem/compass_project#84]
- [x] Develop a `make test` command to execute unit tests efficiently.
- [x] Develop a `make build` command to facilitate the build process.
- [x] Implement a `make run` command to streamline the execution of the project.
- [x] Develop a `make clean` command to remove unnecessary files and reset the project.
- [X] Implement a `make docs` command to generate project documentation. (CANCELED)
- [x] Develop a `make full-run` command to execute the complete process, including email sending.
- [x] Implement a `make help` command to provide usage instructions and command descriptions.

**Comment by Matheus-Homem** [comment]
`Make docs` command was **canceled**, others were **successfully** implemented
